version: '3.8'
services:
  database:
    image: postgres:14.1-alpine
    container_name: database
    environment: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
    networks:
      - banking-system-network

  system:
    image: node:18
    container_name: banking-system
    working_dir: /home/system
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - .:/home/system
    ports: 
      - '3000:3000'
    networks:
      - banking-system-network
    depends_on: 
      - database
    command: bash -c "npm i && npm run build && npm run start:prod"
networks:
  banking-system-network:
    driver: bridge
volumes:
  db:
    driver: local